### ISSUE TITLE
Android 12 zip,txt,pdf all type of document not showing.

### ISSUE THREAD

**Issue by arpitweetech** [DevsOnFlutter/file_manager#17]
in Android 11 and 12 it gives only images and video files and all other types of format files not showing in list please resolve this issue as soon as possible
Thanks!.

**Comment by JobaAdewumi** [comment]
Can you replicate the issue?

**Comment by arpitweetech** [comment]
![Screenshot_20220818-143330](https://user-images.githubusercontent.com/105038957/185356371-2be99847-eaab-48a7-8f24-4b64a0c2f754.jpg)

Here is my mobiles Download Directory and when I open the File manager of my Device it shows me all files like all pdf, txt, and all files but when I used this package and open this file manager example app in the list I got only images not all other files.

**Comment by JobaAdewumi** [comment]
Is it possible you also send the code snippet?

**Comment by JobaAdewumi** [comment]
I have tried to get files for Android 11 and 12 but because of scoped storage it doesn't even work, how did you go around it?

**Comment by hard1k9850** [comment]
I am also facing the same issue. The folder contains images, video, and pdf although it doesn't list the pdf file for some reason.
@4-alok May I request you to please look into this issue if possible? I will also try to figure out what could be the reason

**Comment by hardikm9850** [comment]
Hi @4-alok 
May I request you to please look into this issue if possible? I will also try to figure out what could be the reason

I am also facing the same issue. The folder contains images, video, and pdf although it doesn't list the pdf file for some reason.

**Comment by 4-alok** [comment]
@hardikm9850 I would appreciate it if you could include this in the documentation of [file_manager](https://github.com/DevsOnFlutter/file_manager)

**Comment by hardikm9850** [comment]
Sure @4-alok (apologies for noticing your comment so late)
