### ISSUE TITLE
ValueListenableBuilder<String> widget cannot be marked as needing to build.

### ISSUE THREAD

**Issue by dasaki-gr** [DevsOnFlutter/file_manager#23]
When I try to run the example code given, I get the below error. I'm not familiar with ValueNotifier and ValueListenableBuilder so I can't figure out, what seems to be the issue here.

The following assertion was thrown while dispatching notifications for ValueNotifier<String>:
setState() or markNeedsBuild() called during build.

This ValueListenableBuilder<String> widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.

I have found same issue in :https://stackoverflow.com/questions/71191775/valuelistenablebuilderstring-widget-cannot-be-marked-as-needing-to-build-sets

**Comment by binhdowkm** [comment]
Because FileManagerController was disposed when you navigate to other screen, and this class contains some variables ValueNotifier<String> such as _path, _short,... that widget FileManager need. If you want to quick fix it, you can **go to file_manager.dart and comment function dispose()** .
