### ISSUE TITLE
Need iOS Support!

### ISSUE THREAD

**Issue by divshekhar** [DevsOnFlutter/file_manager#7]
**Description**

The package supports Android for now. Need iOS support for the file_manager.

Need to add `Platform.isIOS` and return a list of all available storage root directories

https://github.com/DevsOnFlutter/file_manager/blob/71f2a74def218fda9d31f4b054f85f06c6fdc4af/lib/file_manager.dart#L237

**Comment by federicoWax** [comment]
Me interesa ayudar
